'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
type E={id:string;name:string,reps:number,label:string,equip:string,icon:string,tips:string[],step?:number};type B={sets:number,a:E,b:E};type W={name:string,sub:string,blocks:B[]};type P='son'|'dad';type Log={weight:number,reps:number,date:string};type Hist=Record<string,Log[]>;
const e=(id:string,name:string,reps:number,label:string,equip:string,icon:string,tips:string[],step=2.5):E=>({id,name,reps,label,equip,icon,tips,step});
const T={press:['Lopatky stáhni k sobě','Chodidla pevně do země','Pohyb veď kontrolovaně'],row:['Záda drž rovná','Lokty táhni k bokům','Pohyb dokonči lopatkami'],squat:['Kolena ve směru špiček','Zpevni střed těla','Tlač přes celá chodidla'],hinge:['Kyčle tlač dozadu','Záda drž neutrálně','Zátěž drž blízko těla'],arms:['Lokty drž stabilní','Bez houpání trupem','Využij plný rozsah'],core:['Žebra drž dole','Zpevni břicho i hýždě','Dýchej pod kontrolou']};
const workouts:W[]=[
{name:'Vršek A',sub:'Síla · tlak & tah',blocks:[
{sets:4,a:e('bench','Benchpress na lavici',8,'8 op.','VELKÁ OSA + LAVICE','🏋️',T.press),b:e('dbrow','Přítahy jednoručky v předklonu',8,'8 op.','JEDNORUČKY','↗',T.row)},
{sets:3,a:e('incline','Tlaky s jednoručkami na šikmé lavici',10,'10 op.','LAVICE + JEDNORUČKY','🏋️',T.press),b:e('ezrow','Přítahy EZ osy v předklonu',10,'10 op.','EZ OSA','↗',T.row)},
{sets:3,a:e('skull','Francouzský tlak ležmo s EZ',12,'12 op.','LAVICE + EZ OSA','💪',T.arms),b:e('lateral','Upažování s jednoručkami vestoje',12,'12 op.','JEDNORUČKY','↔',T.arms,1)},
{sets:3,a:e('curl','Bicepsový zdvih s EZ',12,'12 op.','EZ OSA','💪',T.arms),b:e('pushup','Kliky na zemi',12,'12 op.','VLASTNÍ VÁHA','⬆',T.press)}]},
{name:'Spodek A',sub:'Nohy · plný objem',blocks:[
{sets:4,a:e('squat','Zadní dřep s osou',8,'8 op.','VELKÁ OSA','🏋️',T.squat),b:e('rdl','Rumunský mrtvý tah s jednoručkami',8,'8 op.','JEDNORUČKY','↘',T.hinge)},
{sets:3,a:e('bulgarian','Bulharské dřepy',10,'10 / noha','LAVICE','🦵',T.squat),b:e('stepup','Výstupy na stoličku s jednoručkami',10,'10 / noha','STOLIČKA + JEDNORUČKY','⬆',T.squat)},
{sets:3,a:e('hip','Hip thrust s osou na lavici',12,'12 op.','LAVICE + OSA','◡',T.hinge),b:e('calf','Výpony na lýtka',12,'12 op.','JEDNORUČKY','🦶',T.squat,1)},
{sets:3,a:e('legraise','Přednožování na lavici',12,'12 op.','LAVICE','⬆',T.core),b:e('plank','Plank se zátěží',45,'45 s','PODLOŽKA','▬',T.core,1)}]},
{name:'Vršek B',sub:'Ramena · záda & paže',blocks:[
{sets:4,a:e('ohp','Tlaky nad hlavu vestoje (OHP)',8,'8 op.','VELKÁ OSA','⬆',T.press),b:e('invrow','Inverted rows / přítahy obouruč',8,'8 op.','JEDNORUČKA / OSA','↗',T.row)},
{sets:3,a:e('seated','Tlaky s jednoručkami sedmo',10,'10 op.','LAVICE + JEDNORUČKY','⬆',T.press),b:e('pullover','Pullover s jednoručkou ležmo',10,'10 op.','LAVICE + JEDNORUČKA','↙',T.row)},
{sets:3,a:e('incurl','Bicepsový zdvih na šikmé lavici',12,'12 op.','LAVICE + JEDNORUČKY','💪',T.arms),b:e('reardelt','Upažování v předklonu',12,'12 op.','JEDNORUČKY','↔',T.arms,1)},
{sets:3,a:e('triover','Tricepsová extenze za hlavou',12,'12 op.','JEDNORUČKA','💪',T.arms),b:e('dips','Kliky / dips mezi židlemi',12,'12 op.','ŽIDLE / ZEM','⬆',T.press)}]},
{name:'Spodek B',sub:'Síla · nohy & core',blocks:[
{sets:4,a:e('deadlift','Mrtvý tah s velkou osou',8,'6–8 op.','VELKÁ OSA','🏋️',T.hinge),b:e('goblet','Čelní dřep s jednoručkami',8,'6–8 op.','JEDNORUČKY','🦵',T.squat)},
{sets:3,a:e('lunge','Výpady vzad s osou / jednoručkami',10,'10 / noha','OSA / JEDNORUČKY','🦵',T.squat),b:e('bridge','Glute bridge na zemi',10,'10 op.','PODLOŽKA','◡',T.hinge)},
{sets:3,a:e('situp','Sed-leh na šikmé lavici',15,'15 op.','LAVICE','↗',T.core),b:e('wallsit','Wall sit',45,'45 s','STĚNA','▰',T.core,1)}]}];
const key=(p:P,x:E)=>p+':'+x.id,fmt=(n:number)=>Number.isInteger(n)?''+n:n.toFixed(1);
export default function Home(){const[day,setDay]=useState(0),[bi,setBi]=useState(0),[si,setSi]=useState(0),[done,setDone]=useState<Record<P,boolean>>({son:false,dad:false}),[weights,setWeights]=useState<Record<string,number>>({}),[reps,setReps]=useState<Record<string,number>>({}),[hist,setHist]=useState<Hist>({}),[timer,setTimer]=useState<number|null>(null),[menu,setMenu]=useState(false),[help,setHelp]=useState<P|null>(null),[finish,setFinish]=useState(false),[muted,setMuted]=useState(false),[install,setInstall]=useState<any>(null);const audio=useRef<AudioContext|null>(null),w=workouts[day],b=w.blocks[bi],swap=si%2===1,as=useMemo(()=>({son:swap?b.b:b.a,dad:swap?b.a:b.b}),[b,swap]);
useEffect(()=>{try{setHist(JSON.parse(localStorage.getItem('duogym-history')||'{}'));setWeights(JSON.parse(localStorage.getItem('duogym-weights')||'{}'))}catch{}navigator.serviceWorker?.register('/sw.js');const f=(x:Event)=>{x.preventDefault();setInstall(x)};addEventListener('beforeinstallprompt',f);return()=>removeEventListener('beforeinstallprompt',f)},[]);useEffect(()=>localStorage.setItem('duogym-history',JSON.stringify(hist)),[hist]);useEffect(()=>localStorage.setItem('duogym-weights',JSON.stringify(weights)),[weights]);
const suggested=(p:P,x:E)=>{const l=hist[key(p,x)]||[],last=l.at(-1);if(!last)return p==='son'?20:12.5;return l.slice(-b.sets).length>=b.sets&&l.slice(-b.sets).every(z=>z.reps>=x.reps)?last.weight+(x.step||2.5):last.weight},weight=(p:P,x:E)=>weights[key(p,x)]??suggested(p,x),rep=(p:P,x:E)=>reps[key(p,x)]??x.reps,last=(p:P,x:E)=>(hist[key(p,x)]||[]).at(-1);
const advance=useCallback(()=>{setDone({son:false,dad:false});if(si+1<b.sets)setSi(v=>v+1);else if(bi+1<w.blocks.length){setBi(v=>v+1);setSi(0)}else setFinish(true)},[si,b.sets,bi,w.blocks.length]);
const beep=()=>{const c=audio.current||new AudioContext();audio.current=c;[0,.18,.36].forEach((d,i)=>{const o=c.createOscillator(),g=c.createGain();o.frequency.value=i===2?1040:780;g.gain.setValueAtTime(.18,c.currentTime+d);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+d+.13);o.connect(g).connect(c.destination);o.start(c.currentTime+d);o.stop(c.currentTime+d+.14)})};
useEffect(()=>{if(timer===null)return;if(timer<=0){if(!muted)beep();setTimer(null);advance();return}const id=setTimeout(()=>setTimer(v=>v===null?null:v-1),1000);return()=>clearTimeout(id)},[timer,muted,advance]);
const mark=(p:P)=>{if(done[p])return;const x=as[p];setHist(h=>({...h,[key(p,x)]:[...(h[key(p,x)]||[]),{weight:weight(p,x),reps:rep(p,x),date:new Date().toISOString()}]}));const n={...done,[p]:true};setDone(n);if(n.son&&n.dad)setTimer(90)};const choose=(i:number)=>{setDay(i);setBi(0);setSi(0);setDone({son:false,dad:false});setTimer(null);setMenu(false);setFinish(false)};
return <main className="app"><header><button className="brand" onClick={()=>setMenu(true)}><i>D</i><b>DUO<span>GYM</span></b></button><div className="title"><b>DEN {day+1} · {w.name.toUpperCase()}</b><small>{w.sub}</small></div><div className="tools"><em>● OFFLINE READY</em><button onClick={()=>document.documentElement.requestFullscreen?.()}>⛶</button><button onClick={()=>setMenu(true)}>⚙</button></div><div className="progress"><i style={{width:`${((bi+si/b.sets)/w.blocks.length)*100}%`}}/></div></header><div className="status"><span>● BLOK {bi+1} / {w.blocks.length}</span><b>SÉRIE {si+1} <i>/ {b.sets}</i></b><span>{swap?'⇄ STANOVIŠTĚ PROHOZENA':'● STARTOVNÍ STANOVIŠTĚ'}</span></div>
<section className="grid">{(['son','dad'] as P[]).map(p=>{const x=as[p],old=last(p,x),kg=weight(p,x),rr=rep(p,x);return <article className={p+' '+(done[p]?'done':'')} key={p}><div className="person"><i>{p==='son'?'S':'T'}</i><div><small>UŽIVATEL {p==='son'?'1':'2'}</small><h2>{p==='son'?'SYN':'TÁTA'}</h2></div><em>{p==='son'?'ATLET · 17':'SÍLA & KONDICE'}</em></div><div className="exercise"><div className="visual"><b>{x.icon}</b><small>UKÁZKA POHYBU</small></div><div className="info"><small>{x.equip}</small><h3>{x.name}</h3><div><b>{b.sets} × {x.label}</b><i>PLÁN</i></div><button onClick={()=>setHelp(p)}>◎ TECHNIKA · 3 BODY</button></div></div><div className="last">↗ <small>MINULE</small><b>{old?`${fmt(old.weight)} kg × ${old.reps} op.`:'První záznam'}</b>{old&&suggested(p,x)>old.weight&&<em>+{x.step} KG DOPORUČENO</em>}</div><div className="controls"><label>ZÁTĚŽ <div><button onClick={()=>setWeights(q=>({...q,[key(p,x)]:Math.max(0,kg-(x.step||2.5))}))}>−</button><b>{fmt(kg)}<small>kg</small></b><button onClick={()=>setWeights(q=>({...q,[key(p,x)]:kg+(x.step||2.5)}))}>＋</button></div></label><label>OPAKOVÁNÍ<div><button onClick={()=>setReps(q=>({...q,[key(p,x)]:Math.max(0,rr-1)}))}>−</button><b>{rr}</b><button onClick={()=>setReps(q=>({...q,[key(p,x)]:rr+1}))}>＋</button></div></label></div><button className="donebtn" onClick={()=>mark(p)}>{done[p]?'✓ HOTOVO · ČEKÁM':'✓ HOTOVO'}<small>{done[p]?'DRUHÝ CVIČENEC DOKONČUJE':'ULOŽIT SÉRII'}</small></button></article>})}</section>
<footer><button onClick={()=>setMuted(!muted)}>{muted?'🔇':'♫'}</button><div><small>TRÉNINKOVÝ MIX</small><b>DuoGym Power Session</b></div><i className="eq">▮▯▮▯</i><button className="play" onClick={()=>setMuted(!muted)}>{muted?'▶':'Ⅱ'}</button><strong>Spotify</strong><button className="connect" onClick={()=>window.open('https://open.spotify.com','_blank')}>OTEVŘÍT</button><span>🔊 ━━━━━</span></footer>
{timer!==null&&<div className="overlay"><div className="timer"><small>OBA HOTOVO · ODPOČINEK</small><div style={{'--p':`${timer/90*360}deg`} as React.CSSProperties}><b>{Math.floor(timer/60)}:{String(timer%60).padStart(2,'0')}</b></div><h2>Další série: stanoviště se prohodí</h2><p>Napijte se. Po signálu pokračujte.</p><button onClick={()=>{setTimer(null);advance()}}>PŘESKOČIT ODPOČINEK →</button></div></div>}
{help&&<div className="overlay" onClick={()=>setHelp(null)}><div className="modal" onClick={z=>z.stopPropagation()}><button className="close" onClick={()=>setHelp(null)}>×</button><small>TECHNIKA CVIKU</small><h2>{as[help].name}</h2><ol>{as[help].tips.map((t,i)=><li key={t}><b>{i+1}</b>{t}</li>)}</ol><button className="primary" onClick={()=>setHelp(null)}>ROZUMÍM</button></div></div>}
{menu&&<div className="overlay" onClick={()=>setMenu(false)}><div className="modal" onClick={z=>z.stopPropagation()}><button className="close" onClick={()=>setMenu(false)}>×</button><small>TRÉNINKOVÝ PLÁN</small><h2>Vyber dnešní trénink</h2><div className="days">{workouts.map((q,i)=><button className={i===day?'active':''} onClick={()=>choose(i)} key={q.name}><b>0{i+1}</b><span><strong>{q.name}</strong><small>{q.sub} · {q.blocks.reduce((n,z)=>n+z.sets,0)} sérií</small></span><i>→</i></button>)}</div>{install&&<button className="primary" onClick={()=>{install.prompt();setInstall(null)}}>⊕ NAINSTALOVAT APLIKACI</button>}<button className="reset" onClick={()=>{if(confirm('Opravdu smazat historii?')){setHist({});setWeights({});localStorage.clear()}}}>Smazat historii zařízení</button></div></div>}
{finish&&<div className="overlay"><div className="timer"><div className="bolt">⚡</div><small>TRÉNINK DOKONČEN</small><h2>Skvělá společná práce.</h2><p>{w.blocks.reduce((n,z)=>n+z.sets,0)} sérií na osobu je uloženo. Příště se načtou váhy i doporučení.</p><button onClick={()=>choose((day+1)%4)}>DALŠÍ TRÉNINK →</button><button className="ghost" onClick={()=>choose(day)}>ZOPAKOVAT DEN</button></div></div>}</main>}
