'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
type E={id:string;name:string,reps:number,label:string,equip:string,icon:string,tips:string[],step?:number};type B={sets:number,a:E,b:E};type W={name:string,sub:string,blocks:B[]};type P='son'|'dad';type Log={weight:number,reps:number,date:string};type Hist=Record<string,Log[]>;
const e=(id:string,name:string,reps:number,label:string,equip:string,icon:string,tips:string[],step=2.5):E=>({id,name,reps,label,equip,icon,tips,step});
const T={press:['Lopatky stáhni k sobě','Chodidla pevně do země','Pohyb veď kontrolovaně'],row:['Záda drž rovná','Lokty táhni k bokům','Pohyb dokonči lopatkami'],squat:['Kolena ve směru špiček','Zpevni střed těla','Tlač přes celá chodidla'],hinge:['Kyčle tlač dozadu','Záda drž neutrálně','Zátěž drž blízko těla'],arms:['Lokty drž stabilní','Bez houpání trupem','Využij plný rozsah'],core:['Žebra drž dole','Zpevni břicho i hýždě','Dýchej pod kontrolou']};
const workouts:W[]=[
{name:'Vršek A',sub:'Síla · tlak & tah',blocks:[
{sets:4,a:e('bench','Benchpress na lavici',8,'8 op.','VELKÁ OSA + LAVICE','🏋️',T.press),b:e('dbrow','Přítahy jednoručky v předklonu',8,'8 op.','JEDNORUČKY','↗',T.row)},
{sets:3,a:e('incline','Tlaky s jednoručkami na šikmé lavici',10,'10 op.','LAVICE + JEDNORUČKY','🏋️',T.press),b:e('ezrow','Přítahy EZ osy v předklonu',10,'10 op.','EZ OSA','↗',T.row)},
{sets:3,a:e('skull','Francouzský tlak ležmo s EZ',12,'12 op.','LAVICE + EZ OSA','💪',T.arms),b:e('lateral','Upažování s jednoručkami vestoje',12,'12 op.','JEDNORUČKY','↔',T.arms,1)},
{sets:3,a:e('curl','Bicepsový zdvih s EZ',12,'12 op.','EZ OSA','💪',T.arms),b:e('pushup','Kliky na zemi',12,'12 op.','VLASTNÍ VÁHA','⬆',T.press)}]},
{name:'Spodek A',sub:'Nohy · plný objem',blocks:[
{sets:4,a:e('squat','Zadní dřep s osou',8,'8 op.','VELKÁ OSA','🏋️',T.squat),b:e('rdl','Rumunský mrtvý tah s jednoručkami',8,'8 op.','JEDNORUČKY','↘',T.hinge)},
{sets:3,a:e('bulgarian','Bulharské dřepy',10,'10 / noha','LAVICE','🦵',T.squat),b:e('stepup','Výstupy na stoličku s jednoručkami',10,'10 / noha','STOLIČKA + JEDNORUČKY','⬆',T.squat)},
{sets:3,a:e('hip','Hip thrust s osou na lavici',12,'12 op.','LAVICE + OSA','◡',T.hinge),b:e('calf','Výpony na lýtka',12,'12 op.','JEDNORUČKY','🦶',T.squat,1)},
{sets:3,a:e('legraise','Přednožování na lavici',12,'12 op.','LAVICE','⬆',T.core),b:e('plank','Plank se zátěží',45,'45 s','PODLOŽKA','▬',T.core,1)}]},
{name:'Vršek B',sub:'Ramena · záda & paže',blocks:[
{sets:4,a:e('ohp','Tlaky nad hlavu vestoje (OHP)',8,'8 op.','VELKÁ OSA','⬆',T.press),b:e('invrow','Inverted rows / přítahy obouruč',8,'8 op.','JEDNORUČKA / OSA','↗',T.row)},
{sets:3,a:e('seated','Tlaky s jednoručkami sedmo',10,'10 op.','LAVICE + JEDNORUČKY','⬆',T.press),b:e('pullover','Pullover s jednoručkou ležmo',10,'10 op.','LAVICE + JEDNORUČKA','↙',T.row)},
{sets:3,a:e('incurl','Bicepsový zdvih na šikmé lavici',12,'12 op.','LAVICE + JEDNORUČKY','💪',T.arms),b:e('reardelt','Upažování v předklonu',12,'12 op.','JEDNORUČKY','↔',T.arms,1)},
{sets:3,a:e('triover','Tricepsová extenze za hlavou',12,'12 op.','JEDNORUČKA','💪',T.arms),b:e('dips','Kliky / dips mezi židlemi',12,'12 op.','ŽIDLE / ZEM','⬆',T.press)}]},
{name:'Spodek B',sub:'Síla · nohy & core',blocks:[
{sets:4,a:e('deadlift','Mrtvý tah s velkou osou',8,'6–8 op.','VELKÁ OSA','🏋️',T.hinge),b:e('goblet','Čelní dřep s jednoručkami',8,'6–8 op.','JEDNORUČKY','🦵',T.squat)},
{sets:3,a:e('lunge','Výpady vzad s osou / jednoručkami',10,'10 / noha','OSA / JEDNORUČKY','🦵',T.squat),b:e('bridge','Glute bridge na zemi',10,'10 op.','PODLOŽKA','◡',T.hinge)},
{sets:3,a:e('situp','Sed-leh na šikmé lavici',15,'15 op.','LAVICE','↗',T.core),b:e('wallsit','Wall sit',45,'45 s','STĚNA','▰',T.core,1)}]}];
const key=(p:P,x:E)=>p+':'+x.id,fmt=(n:number)=>Number.isInteger(n)?''+n:n.toFixed(1);
const DEFAULT_SCHEDULE=[1,2,3,4];
const motionFor=(id:string)=>['squat','bulgarian','stepup','calf','goblet','lunge','wallsit'].includes(id)?'squat':['rdl','deadlift','hip','bridge'].includes(id)?'hinge':['dbrow','ezrow','invrow','pullover','reardelt'].includes(id)?'row':['plank','legraise','situp'].includes(id)?'core':['curl','incurl','skull','lateral','triover'].includes(id)?'arms':'press';
function StickFigure({exercise}:{exercise:E}){return <div className={`stick-figure ${motionFor(exercise.id)}`} role="img" aria-label={`Animovaná ukázka: ${exercise.name}`}><div className="floor"/><div className="body"><i className="head"/><i className="torso"/><i className="arm left"/><i className="arm right"/><i className="leg left"/><i className="leg right"/><span className="weight"><b/><b/></span></div></div>}
export default function Home(){const[day,setDay]=useState(0),[bi,setBi]=useState(0),[si,setSi]=useState(0),[done,setDone]=useState<Record<P,boolean>>({son:false,dad:false}),[weights,setWeights]=useState<Record<string,number>>({}),[reps,setReps]=useState<Record<string,number>>({}),[hist,setHist]=useState<Hist>({}),[timer,setTimer]=useState<number|null>(null),[menu,setMenu]=useState(false),[help,setHelp]=useState<P|null>(null),[finish,setFinish]=useState(false),[install,setInstall]=useState<any>(null);const w=workouts[day],b=w.blocks[bi],swap=si%2===1,as=useMemo(()=>({son:swap?b.b:b.a,dad:swap?b.a:b.b}),[b,swap]),today=new Date(),isTrainingDay=today.getDay()>=1&&today.getDay()<=4,todayLabel=today.toLocaleDateString('cs-CZ',{weekday:'long',day:'numeric',month:'long'});
useEffect(()=>{try{setHist(JSON.parse(localStorage.getItem('duogym-history')||'{}'));setWeights(JSON.parse(localStorage.getItem('duogym-weights')||'{}'));const match=DEFAULT_SCHEDULE.indexOf(new Date().getDay());setDay(match>=0?match:0)}catch{}navigator.serviceWorker?.register('./sw.js');const f=(x:Event)=>{x.preventDefault();setInstall(x)};addEventListener('beforeinstallprompt',f);return()=>removeEventListener('beforeinstallprompt',f)},[]);useEffect(()=>localStorage.setItem('duogym-history',JSON.stringify(hist)),[hist]);useEffect(()=>localStorage.setItem('duogym-weights',JSON.stringify(weights)),[weights]);
const suggested=(p:P,x:E)=>{const l=hist[key(p,x)]||[],last=l.at(-1);if(!last)return p==='son'?20:12.5;return l.slice(-b.sets).length>=b.sets&&l.slice(-b.sets).every(z=>z.reps>=x.reps)?last.weight+(x.step||2.5):last.weight},weight=(p:P,x:E)=>weights[key(p,x)]??suggested(p,x),rep=(p:P,x:E)=>reps[key(p,x)]??x.reps,last=(p:P,x:E)=>(hist[key(p,x)]||[]).at(-1);
const advance=useCallback(()=>{setDone({son:false,dad:false});if(si+1<b.sets)setSi(v=>v+1);else if(bi+1<w.blocks.length){setBi(v=>v+1);setSi(0)}else setFinish(true)},[si,b.sets,bi,w.blocks.length]);
useEffect(()=>{if(timer===null)return;if(timer<=0){setTimer(null);advance();return}const id=setTimeout(()=>setTimer(v=>v===null?null:v-1),1000);return()=>clearTimeout(id)},[timer,advance]);
const mark=(p:P)=>{if(done[p]||timer!==null)return;const x=as[p];setHist(h=>({...h,[key(p,x)]:[...(h[key(p,x)]||[]),{weight:weight(p,x),reps:rep(p,x),date:new Date().toISOString()}]}));const n={...done,[p]:true};setDone(n);if(n.son&&n.dad)setTimer(30)};const choose=(i:number)=>{setDay(i);setBi(0);setSi(0);setDone({son:false,dad:false});setTimer(null);setMenu(false);setFinish(false)};
return <main className="app"><header><button className="brand" onClick={()=>setMenu(true)}><i>D</i><b>Duo<span>Gym</span></b></button><div className="title"><b>{w.name}</b><small>{isTrainingDay?todayLabel:`${todayLabel} · volno, připraveno pondělí`}</small></div><div className="tools"><button onClick={()=>setMenu(true)} aria-label="Nastavení">⚙</button></div><div className="progress"><i style={{width:`${((bi+si/b.sets)/w.blocks.length)*100}%`}}/></div></header><div className="status"><span>BLOK {bi+1} Z {w.blocks.length}</span><b>Série {si+1} <i>z {b.sets}</i></b><span>{swap?'⇄ Stanoviště prohozena':'Začínáme'}</span></div>
<section className="grid">{(['son','dad'] as P[]).map(p=>{const x=as[p],old=last(p,x),kg=weight(p,x),rr=rep(p,x);return <article className={p+' '+(done[p]?'done':'')} key={p}><div className="person"><i>{p==='son'?'S':'T'}</i><div><h2>{p==='son'?'Syn':'Táta'}</h2></div>{done[p]&&<span className="ready">Připraven</span>}</div><div className="exercise"><div className="info"><small>{x.equip}</small><h3>{x.name}</h3><div><b>{b.sets} × {x.label}</b></div><button onClick={()=>setHelp(p)}>▶ Ukázat provedení</button></div></div><div className="last"><small>Minule</small><b>{old?`${fmt(old.weight)} kg × ${old.reps}`:'zatím bez záznamu'}</b>{old&&suggested(p,x)>old.weight&&<em>Doporučeno +{x.step} kg</em>}</div><div className="controls"><label>ZÁTĚŽ <div><button aria-label="Snížit zátěž" onClick={()=>setWeights(q=>({...q,[key(p,x)]:Math.max(0,kg-(x.step||2.5))}))}>−</button><b>{fmt(kg)}<small>kg</small></b><button aria-label="Zvýšit zátěž" onClick={()=>setWeights(q=>({...q,[key(p,x)]:kg+(x.step||2.5)}))}>＋</button></div></label><label>OPAKOVÁNÍ<div><button aria-label="Snížit opakování" onClick={()=>setReps(q=>({...q,[key(p,x)]:Math.max(0,rr-1)}))}>−</button><b>{rr}</b><button aria-label="Zvýšit opakování" onClick={()=>setReps(q=>({...q,[key(p,x)]:rr+1}))}>＋</button></div></label></div><button className="donebtn" disabled={done[p]||timer!==null} onClick={()=>mark(p)}>{done[p]?'✓ Série dokončena':'Dokončil jsem sérii'}</button></article>})}</section>
{timer!==null&&<div className="rest-strip"><div><strong>Odpočinek</strong><span>Další série začne sama · {timer} s</span></div><i><b style={{width:`${timer/30*100}%`}}/></i><button onClick={()=>{setTimer(null);advance()}}>Pokračovat hned</button></div>}
{help&&<div className="overlay" onClick={()=>setHelp(null)}><div className="modal technique" onClick={z=>z.stopPropagation()}><button className="close" onClick={()=>setHelp(null)}>×</button><small>JAK NA TO</small><h2>{as[help].name}</h2><StickFigure exercise={as[help]}/><ol>{as[help].tips.map((t,i)=><li key={t}><b>{i+1}</b>{t}</li>)}</ol><button className="primary" onClick={()=>setHelp(null)}>Jasně, jdu cvičit</button></div></div>}
{menu&&<div className="overlay" onClick={()=>setMenu(false)}><div className="modal settings" onClick={z=>z.stopPropagation()}><button className="close" onClick={()=>setMenu(false)}>×</button><small>TRÉNINK</small><h2>Vyber den</h2><p className="hint">DuoGym vybírá automaticky: pondělí až čtvrtek postupně Den 1–4.</p><div className="days">{workouts.map((q,i)=><button className={i===day?'active':''} onClick={()=>choose(i)} key={q.name}><b>{['PO','ÚT','ST','ČT'][i]}</b><span><strong>{q.name}</strong><small>{q.sub} · {q.blocks.reduce((n,z)=>n+z.sets,0)} sérií</small></span><i>→</i></button>)}</div>{install&&<button className="primary" onClick={()=>{install.prompt();setInstall(null)}}>Přidat na plochu</button>}<button className="reset" onClick={()=>{if(confirm('Opravdu smazat historii?')){setHist({});setWeights({});localStorage.clear()}}}>Smazat historii zařízení</button></div></div>}
{finish&&<div className="overlay"><div className="timer"><div className="bolt">⚡</div><small>TRÉNINK DOKONČEN</small><h2>Skvělá společná práce.</h2><p>{w.blocks.reduce((n,z)=>n+z.sets,0)} sérií na osobu je uloženo. Příště se načtou váhy i doporučení.</p><button onClick={()=>choose((day+1)%4)}>DALŠÍ TRÉNINK →</button><button className="ghost" onClick={()=>choose(day)}>ZOPAKOVAT DEN</button></div></div>}</main>}
